# Generated by Django 4.1.13 on 2023-11-21 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("disneyapp", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DisneylandReview",
        ),
    ]
